#!/usr/bin/env python3
"""
Convert face image files to RGB565 C arrays for the ST7735 (160x128 landscape).
Outputs src/faces_bitmaps.h

Run from repo root:  python tools/generate_faces.py
Requires Pillow:     pip install Pillow
"""

import os
import numpy as np
from PIL import Image

W, H = 160, 128  # display resolution (landscape)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

FACES = [
    ('FACE_HAPPY',  'plant-faces-happy-when-watered-task-completed.png'),
    ('FACE_MIDDLE', 'plant-faces-neutral.png'),
    ('FACE_SAD',    'plant-faces-sad.png'),
]


def to_rgb565(img):
    """Composite RGBA over white, resize to display, convert to RGB565."""
    img = img.convert('RGBA')
    bg = Image.new('RGBA', img.size, (255, 255, 255, 255))
    bg.paste(img, mask=img.split()[3])
    bg = bg.convert('RGB').resize((W, H), Image.LANCZOS)
    arr = np.array(bg, dtype=np.uint16)
    r, g, b = arr[:, :, 0], arr[:, :, 1], arr[:, :, 2]
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def write_array(f, name, data):
    flat = data.flatten()
    f.write(f"static const uint16_t {name}[] PROGMEM = {{\n")
    for i, v in enumerate(flat):
        if i % 16 == 0:
            f.write("  ")
        f.write(f"0x{v:04X}")
        if i == len(flat) - 1:
            f.write("\n")
        elif (i + 1) % 16 == 0:
            f.write(",\n")
        else:
            f.write(", ")
    f.write("};\n\n")


def main():
    out_h = os.path.normpath(os.path.join(SCRIPT_DIR, '..', 'src', 'faces_bitmaps.h'))

    with open(out_h, 'w') as f:
        f.write("#pragma once\n")
        f.write("// Auto-generated by tools/generate_faces.py — do not edit manually.\n")
        f.write("#include <pgmspace.h>\n\n")
        f.write(f"#define FACE_W {W}\n")
        f.write(f"#define FACE_H {H}\n\n")

        for name, filename in FACES:
            path = os.path.join(SCRIPT_DIR, filename)
            img = Image.open(path)
            write_array(f, name, to_rgb565(img))
            print(f"{name}: {filename}")

    print(f"Header: {out_h}  ({os.path.getsize(out_h)/1024:.1f} KB)")


if __name__ == '__main__':
    main()
